version: '3'
services:
  apache:
    image: php:8.0-apache
    volumes:
      - .:/var/www/html
    ports:
      - '8080:80'
    networks:
      - server

  mysql:
    image: 'mysql/mysql-server:8.0'
    volumes:
      - 'mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'learn'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    networks:
      - server

networks:
  server:
    driver: bridge
volumes:
  mysql:
    driver: local
